name: lint-source

on: push

jobs:
  lint-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Check code style
        run: yarn format:check
      - name: Check code quality
        run: yarn lint
