name: publish-npm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Publish package
        run: yarn publish --access public
        env:
          # Create your own token at https://github.com/organization/repository/settings/secrets
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
