name: publish-npm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    container: boringcodes/dev-runner:node-16-alpine
    name: With Node.js 16
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Config registry
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org
      - name: Publish package
        run: yarn publish --access public
        env:
          # Create your own token at https://github.com/organization/repository/settings/secrets
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
